# Generated by Django 3.1.7 on 2021-02-25 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LabExam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_date', models.DateField()),
                ('exam_name', models.CharField(max_length=255)),
                ('exam_description', models.TextField()),
                ('total_marks', models.FloatField(blank=True, null=True)),
                ('pass_marks', models.FloatField(blank=True, null=True)),
                ('exam_status', models.BooleanField()),
            ],
        ),
    ]
